spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  datasource:
    url: jdbc:postgresql://dpg-cljgoca4ed1s73bvueng-a:5432/kaskos_850g
    username: kaskos
    password: ZmkGA8c17md9PZ7RNeR0Q6OIMxr1u8z8
  jpa:
    show-sql: true
    format-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 445995943269-25oeki4q6lcnmbisbcsjkrum6bpn8atv.apps.googleusercontent.com
            client-secret: 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
jwt:
  secret-key: 1c3d428e-4ad4-4ac1-b93d-f7fe159d24af
wallet:
  id: 562a73fa-3d19-46a7-a1d1-76ab0dcfda0a
